version: '3.8'
services:
  app:
    build:
      context: ../home-automation-app
      dockerfile: Dockerfile
    env_file:
     - .env.home_automation_app
    volumes:
      - ./:/usr/src/app
    environment:
      FLASK_ENV: development
      FLASK_APP: ./app.py
    ports:
     - "8000:5000"
    restart: always
